# Generated by Django 4.0.2 on 2022-02-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=200)),
                ('estrato', models.CharField(max_length=200)),
                ('comodidades', models.CharField(max_length=200)),
                ('imagenes', models.CharField(max_length=200)),
                ('newimagenes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpd', models.CharField(max_length=200, verbose_name='consultas por dia')),
                ('cpm', models.CharField(max_length=200, verbose_name='consultas por mes')),
                ('sav', models.CharField(max_length=200, verbose_name='similitude average')),
                ('efc', models.CharField(max_length=200, verbose_name='efficiency')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=200)),
            ],
        ),
    ]
