# Generated by Django 4.0.2 on 2022-02-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_apartamentos_newimagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamentos',
            name='precio_nuevo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
