# Generated by Django 4.0.2 on 2022-03-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_apartamentos_precio_nuevo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamentos',
            name='area',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
