# Generated by Django 4.0.2 on 2022-03-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_apartamentos_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamentos',
            name='precio_remo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
