# Generated by Django 4.0.2 on 2022-03-01 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_apartamentos_precio_remo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartamentos',
            name='imagenes',
        ),
        migrations.RemoveField(
            model_name='apartamentos',
            name='newimagenes',
        ),
    ]
