# Generated by Django 4.0.2 on 2022-03-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_remove_apartamentos_imagenes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamentos',
            name='bath',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apartamentos',
            name='bath_new',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apartamentos',
            name='hall',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apartamentos',
            name='hall_new',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apartamentos',
            name='ktc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apartamentos',
            name='ktc_new',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apartamentos',
            name='room',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apartamentos',
            name='room_new',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
