# Generated by Django 4.0.2 on 2022-03-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_apartamentos_bath_apartamentos_bath_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamentos',
            name='bath',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='apartamentos',
            name='bath_new',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='apartamentos',
            name='hall',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='apartamentos',
            name='hall_new',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='apartamentos',
            name='ktc',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='apartamentos',
            name='ktc_new',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='apartamentos',
            name='room',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='apartamentos',
            name='room_new',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
