# Generated by Django 4.0.4 on 2022-05-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_alter_apartamentos_bath_alter_apartamentos_bath_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamentos',
            name='process',
            field=models.ImageField(default='none', max_length=200, upload_to=''),
        ),
    ]
