# Generated by Django 4.0.4 on 2022-07-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_adminuser'),
        ('houses', '0009_apartamentos_process'),
    ]

    operations = [
    ]
